<!DOCTYPE html>
<html>
<head>
    <title>How to generate QR Code with example in Laravel PHP</title>
    <style type="text/css" media="screen">
    	.box{
    		height: 250px;
    		width: 250px;
    		position: relative;
    	}

    	#qr_logo{
    		height: 50px;
    		width: 50px;
    		position: absolute;
    		top: 50%;
    		left: 50%;
    		transform: translate(-50%, -50%);
    	}
    	#qr_logo::after{
    		height: 75px;
    		width: 75px;
    		background-color: #fff;
    	}
    </style>
</head>
<body>
    
<div class="visible-print text-center">
    <h1>Laravel PHP - QR Code Generator Example</h1>
     
    {{-- {!! QrCode::size(400)->generate('2'); !!} --}}

	{{-- {!! $qr_code !!} --}}

	<form action="{{ route('get_qrs') }}" method="get" accept-charset="utf-8">
		<select name="qr_code">
			<option disabled selected>Qr Codes</option>
			@foreach($code_number as $element)
                 <option value="{{ $element->qr_unique_number }}">{{ $element->code_number }}</option>
            @endforeach
		</select>
		<button type="submit">submit</button>
	</form>

	<br><br><br>

	<div class="box">
		<img src="data:image/png;base64, {!! base64_encode($qr_code) !!}">
		<img src="{{asset('assets/img/squart_logo_qr.png')}}" alt="" id="qr_logo">
	</div>
	{{-- {!! $qr_code !!} --}}
     
    <p>QR Code Example generated by laravel package</p>
</div>

{{-- <div class="visible-print text-center">
	<img src="data:image/png;base64, {!! base64_encode(QrCode::format('svg')->size(250)->errorCorrection('H')->generate('Make me into an QrCode!')) !!} ">

	{!! QrCode::format('svg')->size(250)->errorCorrection('H')->generate('Make me into an QrCode!') !!}

	
</div> --}}
    
</body>
</html>