<!DOCTYPE html>
<html>
<head>
    <title>How to generate QR Code with example in Laravel PHP</title>
</head>
<body>
    
<div class="visible-print text-center">
    <h1>Laravel PHP - QR Code Generator Example</h1>
     
    {{-- {!! QrCode::size(400)->generate('2'); !!} --}}

	{{-- {!! $qr_code !!} --}}

	<form action="{{ route('get_qrs') }}" method="get" accept-charset="utf-8">
		<select name="qr_code">
			<option disabled selected>Qr Codes</option>
			@foreach($code_number as $element)
                 <option value="{{ $element->qr_unique_number }}">{{ $element->code_number }}</option>
            @endforeach
		</select>
		<button type="submit">submit</button>
	</form>

	<br><br><br>

	<img src="data:image/png;base64, {!! base64_encode($qr_code) !!}">

	{{-- {!! $qr_code !!} --}}
     
    <p>QR Code Example generated by laravel package</p>
</div>

{{-- <div class="visible-print text-center">
	<img src="data:image/png;base64, {!! base64_encode(QrCode::format('svg')->size(250)->errorCorrection('H')->generate('Make me into an QrCode!')) !!} ">

	{!! QrCode::format('svg')->size(250)->errorCorrection('H')->generate('Make me into an QrCode!') !!}

	
</div> --}}
    
</body>
</html>